call plug#begin('~/.vim/plugged')
	Plug 'scrooloose/nerdtree'
	Plug 'valloric/youcompleteme'
	Plug 'Yggdroot/indentLine'
	Plug 'kien/ctrlp.vim'
	Plug 'jistr/vim-nerdtree-tabs'
	Plug 'vim-airline/vim-airline'
call plug#end()
let g:nerdtree_tabs_open_on_console_startup=1
